const mongoose = require('mongoose');

const schemaauth = mongoose.Schema({
  projectName: String,
  context: String,
  namespace: String,
  testName: String,
  testResult: String,
  testId: String,
  testDuration: Number,
  passTest: Boolean,
  GITLAB_USER_ID: String,
  CI_PROJECT_URL: String,
  CI_PROJECT_TITLE: String,
  CI_PROJECT_NAME: String,
  CI_PROJECT_ID: String,
  CI_PIPELINE_ID: String,
  CI_COMMIT_TAG: String,
  CI_COMMIT_REF_NAME: String,
  CI_COMMIT_SHA: String,
  CI_COMMIT_MESSAGE: String,
  CI_COMMIT_TITLE: String,
  GITLAB_USER_EMAIL: String,
  GITLAB_USER_ID: String,
  auth_CHECK_LOGIN_CURL: String,
  auth_CHECK_SWAGGER_APIS: String,
  auth_CHECK_SWAGGER_PUBLIC_APIS: String,
  auth_CHECK_VOLUMES: String,
  auth_CREATE_CONFIG_FILE: String,
  auth_CHECK_PODS_LOGS: String,
  auth_CHECK_CONDITIONS: String,
  auth_CHECK_INGRESS: String,
  auth_CHECK_IF_ALL_PODS_ARE_ACTIVE: String,
  auth_NAMESPACE: String,
  auth_AUTO_DETECT: String,
  auth_SCANNER_LOGIN: String,
  auth_CURL_LOGIN: String,
  auth_SCANNER_API_METHOD: String,
  auth_CRITERIAL: String,
  auth_ASSERT_CURL: String,
  auth_CONTEXT: String,
  auth_ENVIRONMENT: String,
  auth_ENVIRONMENT_VARIABLE: String,
  auth_PROJECT_NAME: String,
  auth_SKIP_PROMPTS: String,
});

module.exports.auth = mongoose.model('auth', schemaauth);
module.exports.schemaauth = schemaauth;
